services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: "10000"