services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-tel poppler-utils
      pip install -r requirements.txt
    startCommand: python app.py
