services:
  - type: web
    name: flask-keyword-filter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    build:
      packages:
        - poppler-utils
        - tesseract-ocr
