services:
  - type: web
    name: pdf-ocr-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils tesseract-ocr tesseract-ocr-eng tesseract-ocr-tel
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: "10000"